name: Build

on: [push, pull_request]

jobs:
  build:
    runs-on: windows-2022

    steps:
      - uses: actions/checkout@v4

      - uses: lukka/run-vcpkg@v11
  
      - uses: ilammy/msvc-dev-cmd@v1


      - name: Configure
        run: cmake --preset x64-Debug

      - name: Build
        run: cmake --build out/build/x64-Debug
