name: Build

on: [push, pull_request]

jobs:
  build:
    runs-on: windows-latest

    env:
      VCPKG_BINARY_SOURCES: clear;x-gha,readwrite

    steps:
      - uses: actions/checkout@v4

      - uses: lukka/run-vcpkg@v11
  
      - uses: ilammy/msvc-dev-cmd@v1

      - name: Cache vcpkg installed folder
        uses: actions/cache@v4
        with:
          path: out/build/**/vcpkg_installed
          key: vcpkg-installed-${{ runner.os }}-${{ hashFiles('vcpkg.json', 'CMakePresets.json') }}

      - name: Configure
        run: cmake --preset x64-Debug

      - name: Build
        run: cmake --build out/build/x64-Debug
